# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ehouarn on the threadmill
email: ehouarn.perret@outlook.com
description: "I truly enjoy programming and like rambling about it =]"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ehouarn-perret.github.io" # the base hostname & protocol for your site

# Social links 
# uncomment the options you wish to display, and add your own URL 
social_links: 
  github_url: "https://github.com/ehouarn-perret/" 
  linkedin_url: "https://www.linkedin.com/in/ehouarnperret" 
  website_url: "http://ehouarn-perret.github.io" 

github_username: ehouarn-perret
linkedin_username: ehouarnperret
disclaimer: The opinions and ideas expressed here are solely my own and do not reflect the views of my employer or the organizations to which I belong.

# Build settings
markdown: kramdown
