title: Ehouarn on the treadmill
author: Ehouarn Perret
description: > 
  Notes and ramblings about software development...
disclaimer: > 
  Disclaimer: Opinions expressed are solely my own and do not express the views or opinions of my employer.

# social links
email: ehouarn.perret@outlook.com
github_username: ehouarn-perret
facebook_username: ehouarn.perret
linkedin_username: ehouarnperret
phone_number: 33-7-66-03-07-03
whatsapp_username: 33766030703
skype_username: ehouarn.perret@outlook.com
stackoverflow_username: 4636721
rss: rss

disqus_shortname: ehouarnperret

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
